import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import StatusBadge from "../components/StatusBadge";
import api from "../api/axios";

export default function Summary() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const caseId = params.get("caseId");
  const [caseData, setCaseData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const endpoint = caseId ? `/citizen/cases/${caseId}` : "/citizen/cases/latest";
    api.get(endpoint)
      .then((r) => setCaseData(r.data?.case || r.data))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [caseId]);

  if (loading) {
    return (
      <div className="min-h-screen bg-parchment flex flex-col">
        <Navbar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-secondary opacity-50 text-sm">Loading summary…</div>
        </div>
      </div>
    );
  }

  const summary = caseData?.aiSummary || "Your case has been processed. The AI-generated summary will appear here once analysis is complete.";
  const category = caseData?.category || "Legal Matter";

  return (
    <div className="min-h-screen bg-parchment flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto w-full px-4 sm:px-6 py-10">
        <div className="mb-8">
          <p className="label-caps mb-1">Case Summary</p>
          <h1 className="page-title mb-2">AI-Generated Brief</h1>
          <p className="text-text-secondary">Review the case overview generated by LEX AI based on your answers.</p>
        </div>

        <div
          className="rounded-xl overflow-hidden shadow-courtroom mb-6"
          style={{ border: "1px solid rgba(184,134,11,0.25)" }}
        >
          <div
            className="px-6 py-4 flex items-center justify-between"
            style={{ background: "linear-gradient(135deg, #5C3A21 0%, #7A4E2D 100%)" }}
          >
            <div className="flex items-center gap-3">
              <ScalesIcon className="w-5 h-5 text-secondary" />
              <h2
                className="text-secondary font-bold text-lg"
                style={{ fontFamily: "'Playfair Display', serif" }}
              >
                {category}
              </h2>
            </div>
            <StatusBadge status={caseData?.status || "review"} />
          </div>

          <div
            className="px-6 py-6"
            style={{ background: "linear-gradient(180deg, #FAF9F6 0%, #F5F2EB 100%)" }}
          >
            <p className="label-caps mb-4">AI Summary</p>
            <div
              className="text-text-primary text-sm leading-relaxed whitespace-pre-wrap border-l-4 pl-5 py-1"
              style={{ borderColor: "#C5A059", fontFamily: "'Source Serif 4', serif" }}
            >
              {summary}
            </div>
          </div>

          {caseData?.answers && Object.keys(caseData.answers).length > 0 && (
            <div className="px-6 pb-6" style={{ background: "#F5F2EB" }}>
              <div className="border-t border-accent border-opacity-20 pt-5">
                <p className="label-caps mb-4">Your Responses</p>
                <div className="space-y-3">
                  {Object.entries(caseData.answers).map(([i, ans]) => (
                    <div key={i} className="bg-ivory rounded px-4 py-3 border border-accent border-opacity-10">
                      <p className="text-xs text-secondary font-semibold mb-1">Answer {Number(i) + 1}</p>
                      <p className="text-sm text-text-primary">{ans}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={() => navigate(`/citizen/checklists${caseId ? `?caseId=${caseId}` : ""}`)}
            className="btn-primary flex-1 text-center"
          >
            Documents & Checklists →
          </button>
          <button
            onClick={() => navigate(`/citizen/procedure${caseId ? `?caseId=${caseId}` : ""}`)}
            className="btn-secondary flex-1 text-center"
          >
            Legal Procedure →
          </button>
        </div>
      </main>
      <Footer />
    </div>
  );
}

function ScalesIcon({ className }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
      <path strokeLinecap="round" strokeLinejoin="round" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
    </svg>
  );
}
